name: Python Tests

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out target branch
        if: github.event_name == 'push'
        uses: actions/checkout@v4

      - name: Check out target branch
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        working-directory: ./TradeStock
        run: |
          python -m unittest discover
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Check out target branch
        if: github.event_name == 'push'
        uses: actions/checkout@v4

      - name: Check out target branch
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Check code formatting with black
        uses: psf/black@stable
        with:
          options: "--check --verbose --diff"
          src: "./TradeStock"